version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: comp3133_backend
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: comp3133_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped